django_base/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django_base.views import index, sobrenosotros
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('paginas/', include('paginas.urls')),
    path('',  include('users.urls', namespace='users')),
    path('sobre-nosotros/', sobrenosotros, name ='sobrenosotros')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
from paginas.views import listar_paginas, crear_pagina, buscar_pagina, detalle_pagina, borrar_pagina, listar_seccion, valorar_pagina, listar_paginas2, actualiza_vista, listar_seccion, crear_seccion
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    path('', listar_paginas, name = 'paginas'),
    path('<int:seccion_id>/', listar_paginas, name = 'paginas'),
    path('crear-pagina/', crear_pagina.as_view(), name = 'crear_pagina'),
    path('listar-paginas2/', listar_paginas2, name = 'listar_paginas2'),
    path('buscar-pagina/', buscar_pagina, name = 'buscar_pagina'),
    path('detalle-pagina/<int:pk>/', detalle_pagina, name = 'detalle_pagina'),
    path('borrar-pagina/<int:pk>/', borrar_pagina, name = 'borrar_pagina'),
    #path('actualizar-pagina/<int:pk>/', actualizar_pagina, name = 'actualizar_pagina'),
    path('valorar-pagina/', valorar_pagina, name = 'valorar_pagina'),
    path('listar-paginas2/', listar_paginas2, name = 'listar_paginas2'),
    path('actualiza-vista/<int:pk>/', actualiza_vista, name='actualiza_vista'),
    path('listar-seccion/', listar_seccion, name = 'listar_seccion'),
    path('crear-seccion/', crear_seccion, name = 'crear_seccion')



]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('borrar/<slug:slug>', views.borrar_usuario, name = 'borrar'),
    path('edit/<slug:slug>', views.edituser_list, name = 'edit'),
    path('edit2/<slug:slug>', views.edituser_view, name = 'edit2'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path('signup/', views.signup_view, name='signup'),   
    path('logout/', views.logout_view, name='logout'),
    path('change/',views.changepassword, name='change'),
    path('list/', views.user_list, name = 'list'),
    path('crear/', views.signup_view, name = 'crear'),

]

paginas/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings


# Create your models here.
class Secciones(models.Model):
    nombre = models.CharField(max_length=100)
    habilitada = models.BooleanField(default=False)
    tstamp = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = 'seccion'
        verbose_name_plural = 'secciones'
    def __str__(self):
        return self.nombre

class Paginas(models.Model):
    titulo = models.CharField(max_length=100)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)#--------------------
    secciones = models.ManyToManyField(Secciones)
    fecha = models.DateTimeField()
    copete = models.CharField(max_length=500)
    cuerpo = RichTextField(blank=True, null=True)
    imagen = models.ImageField(upload_to='imagenes', blank=True)
    imagen_epigrafe = models.CharField(max_length=50, blank=True, null=True)    
    habilitada = models.BooleanField(default=False)
    votos = models.IntegerField(default=0)
    puntaje = models.IntegerField(default=0)
    tstamp = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = 'pagina'
        verbose_name_plural = 'paginas'
    def __str__(self):
        return self.titulo

paginas/forms.py
from django import forms
from paginas.models import Paginas, Secciones

class Pagina_form(forms.ModelForm):
    class Meta:
        model = Paginas
        fields = '__all__'



class Seccion_form(forms.ModelForm):
    class Meta:
        model = Secciones
        fields = '__all__'

paginas/views.py
from sqlite3 import TimestampFromTicks
from django.shortcuts import render, get_object_or_404, redirect
from paginas.models import Paginas, Secciones
from paginas.forms import Pagina_form, Seccion_form
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.urls import reverse
from django.contrib.auth.forms import UserChangeForm

# Create your views here.
#@login_required       
def listar_paginas(request, seccion_id=""):
    if seccion_id == "":
        paginas = Paginas.objects.filter(habilitada=True).order_by('-fecha')
    else:
        paginas = Paginas.objects.filter(habilitada=True, secciones__id=seccion_id).order_by('-fecha')
        seccion = Secciones.objects.get(id=seccion_id)
    pagina = request.GET.get('page', 1)
    paginador = Paginator(paginas, 4)
    try:
        paginas = paginador.page(pagina)
    except PageNotAnInteger:
        paginas = paginador.page(1)
    except EmptyPage:
        paginas = paginador.page(paginador.num_pages)
    secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
    if seccion_id == "":
        context = {'paginas':paginas, 'secciones':secciones}
    else:
        context = {'paginas':paginas, 'secciones':secciones, 'seccion':seccion}
    return render(request, 'paginas.html', context=context)

@login_required
def listar_paginas2(request): # borré seccion=""
    paginas = Paginas.objects.all # saque order_by('-fecha')
    secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
    context = {'paginas':paginas, 'secciones':secciones}
    return render(request, 'listar_paginas2.html', context=context)    


def detalle_pagina(request, pk):
    try:
        pagina = Paginas.objects.get(id=pk)
        if pagina.votos > 0:
            pagina.valoracion = pagina.puntaje / pagina.votos
        else: 
            pagina.valoracion = 0
        secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
        context = {'pagina':pagina, 'secciones':secciones}
        return render(request, 'detalle_pagina.html', context=context)
    except:
        context = {'error':'La página no existe'}
        return render(request, 'paginas.html', context=context)

def valorar_pagina(request):
    puntaje=request.POST.get('puntaje')
    id=request.POST.get('id')
    pagina = Paginas.objects.get(id=id)
    votos = pagina.votos
    nuevos_votos = votos + 1
    nuevo_puntaje = pagina.puntaje + int(puntaje)
    pagina.votos = nuevos_votos
    pagina.puntaje = nuevo_puntaje
    pagina.save()

    print(puntaje, id)
    return JsonResponse({'texto': 'Su valoracion fue recibida. Muchas gracias.'})



###############################################################
@login_required
def listar_paginas2(request): # borré seccion=""
    paginas = Paginas.objects.all # saque order_by('-fecha')
    secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
    context = {'paginas':paginas, 'secciones':secciones}
    return render(request, 'listar_paginas2.html', context=context)



# update view for details
def actualiza_vista(request, pk):
    obj = get_object_or_404(Paginas, id = pk)
    if request.method == "POST":
        form = Pagina_form(request.POST, request.FILES, instance = obj)
        if form.is_valid():
            form.save()
            return redirect("/paginas/listar-paginas2/")
    else:
        pagina = Paginas.objects.get(id=pk)
        secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
        form = Pagina_form(instance = pagina)
        context = {'form':form,'id':pk, 'secciones':secciones}
        return render(request, 'actualiza_vista.html',context)




################################################################
class crear_pagina(LoginRequiredMixin, CreateView):
    model = Paginas
    template_name = 'crear_pagina.html'
    fields = '__all__'
    def get_success_url(self):
        return reverse('index')


def borrar_pagina(request, pk):
    try:
        if request.method == 'GET':
            pagina = Paginas.objects.get(id=pk)
            context = {'pagina':pagina}
            return render(request, 'borrar_pagina.html', context=context)
        else:
            pagina = Paginas.objects.get(id=pk)
            pagina.delete()
            paginas = Paginas.objects.filter(habilitada=True).order_by('-fecha')
            secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
            context = {'paginas':paginas, 'secciones':secciones}
            return render(request, 'listar_paginas2.html', context=context)
        
    except:
        context = {'error':'La pagina no existe'}
        return render(request, 'borrar_pagina.html', context=context)

# def buscar_pagina(request):
#     palabra_busqueda = request.GET['buscar']
#     paginas = Paginas.objects.filter(titulo__icontains = palabra_busqueda)
#     if paginas.exists():
#         print(1)
#         context = {'paginas':paginas}
#         return render(request, 'buscar_paginas.html', context = context)
#     else:
#         print(2)
#         context = {'errors':'No se encontro el valor correcto'}
#     return render(request, 'buscar_paginas.html', context = context)

def buscar_pagina(request):
    paginas = Paginas.objects.filter(titulo__icontains=request.GET['buscar'])
    if paginas.exists():
        context = {'paginas':paginas}
    else:
        context = {'errors':'No se encontro la página'}
    return render(request, 'buscar_paginas.html', context = context)

###################################################################
###################################################################
###################################################################
#secciones // crear seccion // listar seccion 

@login_required
def crear_seccion(request):
    if request.method == 'GET':
        form = Seccion_form()
        #secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
        context = {'form':form}
        return render(request, 'crear_seccion.html', context=context)
    elif request.method == 'POST':        
        form = Seccion_form(request.POST, request.FILES)
        secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
        if form.is_valid():
            nueva_seccion = Secciones.objects.create(
                nombre = form.cleaned_data['nombre'],
                habilitada = form.cleaned_data['habilitada'],
                #tstamp = form.cleaned_data['tstamp'],
            )
            context = {'nueva_seccion':nueva_seccion, 'secciones':secciones}
        else:
            context = {'errors':form.errors, 'secciones':secciones}
        return render(request, 'crear_seccion.html', context = context)

    else:
        return redirect('login')




@login_required
def listar_seccion(request): # borré seccion=""
    secciones = Secciones.objects.all
    context = {'secciones':secciones}
    return render(request, 'listar_seccion.html', context=context)


###################################################################
###################################################################
###################################################################

templates/actualiza_vista.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
    {% if form %}
        <h2 style="margin-left:30rem">Complete los campos a actualizar</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table wifth="100%">
                {{form.media}}
                {{form.as_table}}
            </table>
            <input type="submit" , value="Enviar">
        </form>
    {% elif nueva_pagina %}
        <h2 style="color:green; margin-left:33rem">Pagina Actualizada</h2>
        <div class="card" style="width: 18rem;background-color: aqua;margin-top:4rem;margin-left:35rem">
            <div class="card-body">
                <h5 class="card-title">Titulo: {{nueva_pagina.titulo}}</h5>
                <p class="card-text">Copete: {{nueva_pagina.copete}}</p>
                <p class="card-text">Fecha: {{nueva_pagina.fecha}}</p>
            </div>
        </div>
    {% else %}
        <h2 style = "color:red; margin-left:25rem"> Ocurrio un error en la carga de la pagina</h2>
        <div style = "margin-left:25rem;">{{errors}}</div>
    {% endif %}
{% endblock %}

templates/base_.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TechNews - HTML and CSS Template</title>

	<!-- favicon -->
	<link href="{% static '/img/favicon.png' %}" rel=icon>

	<!-- web-fonts -->
	<link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>

	<!-- Bootstrap -->
	<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- font-awesome -->
	<link href="{% static '/fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Mobile Menu Style -->
	<link href="{% static '/css/mobile-menu.css' %}" rel="stylesheet">

	<!-- Owl carousel -->
	<link href="{% static '/css/owl.carousel.css' %}" rel="stylesheet">
	<link href="{% static '/css/owl.theme.default.min.css' %}" rel="stylesheet">
	<!-- Theme Style -->
	<link href="{% static '/css/style.css' %}" rel="stylesheet">

	<style>
	.test{
		height:40px;
		width:40px;
	}
	</style>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar">
	{% include "user/login.html" %}
	{% include "user/change_password.html" %}
	<div id="main-wrapper">
	<!-- Page Preloader -->
	<div id="preloader">
		<div id="status">
			<div class="status-mes"></div>
		</div>
	</div>
	<!-- preloader -->

	<div class="uc-mobile-menu-pusher">
		<div class="content-wrapper">
			<section id="header_section_wrapper" class="header_section_wrapper">
				<div class="container">
					<div class="header-section">
						<div class="row">
							<div class="col-md-4">
								<div class="left_section">
									<span class="date">
										{% now "l" %} .
									</span>
									<!-- Date -->
									<span class="time">
										{% now "d F . Y" %}
									</span>
									<!-- Time -->
									<div class="social">
										<a href="https://www.facebook.com/"class="icons-sm fb-ic"><i class="fa fa-facebook"></i></a>
										<!--Twitter-->
										<a href="https://www.twitter.com"class="icons-sm tw-ic"><i class="fa fa-twitter"></i></a>
										<!--Google +-->
										<a href="https://www.instagram.com/" class="icons-sm inst-ic"><i class="fa fa-instagram"> </i></a>
										<!--Linkedin-->
										<a href="https://www.tumblr.com" class="icons-sm tmb-ic"><i class="fa fa-tumblr"> </i></a>
										<!--Pinterest-->
										<a class="icons-sm rss-ic"><i class="fa fa-rss"> </i></a>
									</div>
									<!-- Top Social Section -->
								</div>
								<!-- Left Header Section -->
							</div>
							<div class="col-md-4">
								<div class="logo">
									<a href="/"><img src="{% static '/img/logo.png' %}" alt="Tech NewsLogo"></a>
								</div>
								<!-- Logo Section -->
							</div>
							<div class="col-md-4">
								<div class="right_section">
									<ul class="nav navbar-nav">
										{% if request.user.is_authenticated %}
																
											<button type="button"
													class="btn btn-secondary btn-lg" 
													data-toggle="modal"
													style="text-align:center;" 
													data-target="#modal_change">CAMBIAR CONTRASEÑA<br>{{ user.first_name }}
											</button>											 											
											<a href={% url 'users:profile' %}>
												<img src={{ user.profile_pic.url }} class="rounded" height="40" width='40' alt="" loading="lazy" />
											</a>
										{% else %}
											<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal_login">Iniciar Sesion / Registrarse</button>
											{% for message in messages %}
											<!-- <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'> -->
												<br>{{ message }}
											<!-- </div> -->
											{% endfor %}											
										{% endif %}
										<!--<li class="dropdown lang">
											<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
												data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">En <i
												class="fa fa-angle-down"></i></button>
											<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
												<li><a href="#">Bn</a></li>
											</ul>
										</li>-->
									</ul>
									<!-- Language Section -->

									<ul class="nav-cta hidden-xs">
										<li class="dropdown">
											<a href="#" data-toggle="dropdown" class="dropdown-toggle">
												<i class="fa fa-search"></i>
											</a>
											<ul class="dropdown-menu">
												<li>
													<div class="head-search">
														<form role="form">
															<!-- Input Group -->
															<div class="input-group">
																<input type="text" class="form-control" placeholder="Type Something"> 
																	<span class="input-group-btn">
																		<button type="submit" class="btn btn-primary">Search</button>
																	</span>
															</div>
														</form>
													</div>
												</li>
											</ul>
										</li>
									</ul>
									<!-- Search Section -->
								</div>
								<!-- Right Header Section -->
							</div>
						</div>
					</div>
					<!-- Header Section -->
					{% include "menu.html" with secciones=secciones%}
				</div>
				<!-- .container -->
			</section>
			<!-- header_section_wrapper -->
		<section id="entity_section" class="entity_section">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					{% block contenido %}
					{% endblock %}
				</div>
				<!-- col-md-8 -->
				{% include "noticias.html" %}
    
				<!-- jquery Core-->
				<script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>

				<!-- Bootstrap -->
				<script src="{% static '/js/bootstrap.min.js' %}"></script>

				<!-- Theme Menu -->
				<script src="{% static '/js/mobile-menu.js' %}"></script>

				<!-- Owl carousel -->
				<script src="{% static '/js/owl.carousel.min.js' %}"></script>

				<!-- Theme Script -->
				<script src="{% static '/js/script.js' %}"></script>

</body>
</html>

templates/base_backoffice.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TechNews - HTML and CSS Template</title>

	<!-- favicon -->
	<link href="{% static '/img/favicon.png' %}" rel=icon>

	<!-- web-fonts -->
	<link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>

	<!-- Bootstrap -->
	<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- font-awesome -->
	<link href="{% static '/fonts/font-awesome/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Mobile Menu Style -->
	<link href="{% static '/css/mobile-menu.css' %}" rel="stylesheet">

	<!-- Owl carousel -->
	<link href="{% static '/css/owl.carousel.css' %}" rel="stylesheet">
	<link href="{% static '/css/owl.theme.default.min.css' %}" rel="stylesheet">
	<!-- Theme Style -->
	<link href="{% static '/css/style.css' %}" rel="stylesheet">

	<style>
	.test{
		height:40px;
		width:40px;
	}
	</style>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar">
	{% include "user/login.html" %}
	{% include "user/change_password.html" %}
<div id="main-wrapper">
	<!-- Page Preloader -->
	<div id="preloader">
		<div id="status">
			<div class="status-mes"></div>
		</div>
	</div>
	<!-- preloader -->
	<div class="uc-mobile-menu-pusher">
		<div class="content-wrapper">
			<section id="header_section_wrapper" class="header_section_wrapper">
				<div class="container">
					{% include "header.html" %}					<!-- Header Section -->
					{% include "menu.html" with secciones=secciones%}
				</div>
				<!-- .container -->
			</section>
			<!-- header_section_wrapper -->
			<section id="entity_section" class="entity_section">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							{% block contenido %}
							{% endblock %}
						</div>
						<!-- col-md-8 -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</section>
			<!-- entity_section -->
			{% include "pie.html" %}
		</div>
		<!-- #content-wrapper -->
	</div>
	<!-- .offcanvas-pusher -->
	<a href="#" class="crunchify-top"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
	{% include "menu_celulares.html" %}
	<!-- .uc-mobile-menu -->
</div>
<!-- #main-wrapper -->
<!-- jquery Core-->
<script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static '/js/bootstrap.min.js' %}"></script>

<!-- Theme Menu -->
<script src="{% static '/js/mobile-menu.js' %}"></script>

<!-- Owl carousel -->
<script src="{% static '/js/owl.carousel.min.js' %}"></script>

<!-- Theme Script -->
<script src="{% static '/js/script.js' %}"></script>

</body>
</html>

templates/buscar_paginas.html
{% extends 'base.html' %}

{% block titulo %}
    Buscador de Páginas
{% endblock %}


{% block contenido %}
<h1 style="margin-left:30rem">Resultado de Búsqueda</h1>
{% if paginas %}
    <div class="d-flex" style="margin-top:5rem; margin-left:7rem">
        {% for pagina in paginas %}
            
            <div class="d-flex" style="margin-top:5rem; margin-left:7rem">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{pagina.titulo}}</h5>
                        <p class="card-text">{{pagina.fecha}}</p>
                        <a href="/paginas/detalle-pagina/{{pagina.id}}" class="btn btn-primary">Ver</a>
                    </div>
                </div>
            </div>
        
        {% endfor %}
    </div>
{% endif %}


<div style = "color:red; margin-left:25rem">{{errors}}</div>

{% endblock %}

templates/crear_seccion.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
    {% if form %}
        <h2 style="margin-left:30rem">Complete los campos de la nueva Seccion</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table wifth="100%">
                {{form.media}}
                {{form.as_table}}
            </table>
            <input type="submit" , value="Enviar">
        </form>
    {% elif nueva_seccion %}
        <h2 style="color:green; margin-left:33rem">Nueva Seccion creada</h2>
        <div class="card" style="width: 18rem;background-color: aqua;margin-top:4rem;margin-left:35rem">
            <div class="card-body">
                <h5 class="card-title">Nombre: {{nueva_seccion.nombre}}</h5>
                <p class="card-text">Habilitada: {{nueva_seccion.habilitada}}</p>
                <p class="card-text">tstamp: {{nueva_seccion.tstamp}}</p>
            </div>
        </div>
    {% else %}
        <h2 style = "color:red; margin-left:25rem"> Ocurrio un error en la carga de la pagina</h2>
        <div style = "margin-left:25rem;">{{errors}}</div>
    {% endif %}
{% endblock %}

templates/crear_usuario.html
{% extends 'base.html' %}

{% block titulo %}
Crear Usuario
{% endblock %}

{% block contenido %}

    {% if form %}
        <h2 style="margin-left:30rem">Complete los campos del nuevo Usuario</h2>
        <form action="" method="POST" style="margin-left:40rem;margin-top:7rem" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" , value="Enviar">
        </form>

    {% elif nuevo_usuario %}
        <h2 style="color:green; margin-left:33rem">Nuevo Usuario Creado</h2>
        <div class="card" style="width: 18rem;background-color: aqua;margin-top:4rem;margin-left:35rem">
            <div class="card-body">
                <h5 class="card-title">Nombre y Apellido: {{nuevo_usuario.nombre}} {{nuevo_usuario.apellido}}</h5>
                <p class="card-text">Nickname: {{nuevo_usuario.nickname}}</p>
                <p class="card-text">Email: {{nuevo_usuario.email}}</p>
                <p class="card-text">Clave: {{nuevo_usuario.clave}}</p>
                <p class="card-text">Perfil id: {{nuevo_usuario.perfilid}}</p>
                <p class="card-text">Habilitado: {{nuevo_usuario.habilitado}}</p>
            </div>
        </div>



        {% else %}
        <h2 style = "color:red; margin-left:25rem"> Ocurrio un error en la carga de la pagina</h2>
        
            <div style = "margin-left:25rem;">{{errors}}</div>
        
    {% endif %}
{% endblock %}

templates/listar_seccion.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
<table width="100%" class="table-bordered">
    <tbody>
        
        <tr style= "background-color: #100e0f">
            <td>
                <h3 style="color:rgb(234, 235, 240)"> Nombre de la Seccion:</h3>
            </td>>
                <td>
                    <h3 style="color:rgb(238, 236, 243)" >Habilitado: </h3>
                    </td>>
        </tr>
        {% for seccion in secciones %}
            <tr>
                <td>
                    <li><a href="/paginas/{{seccion.id}}">{{seccion.nombre}} </a></li>
                </td>
                <td>
                    {{seccion.habilitada}}
                    </td>
            </tr>
        {% endfor %}
    </tbody>
</table>    
{% endblock %}

templates/prueba.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
<form id="edit" class="text-center" action="{% url 'users:edit'%}" method="post">
    {% csrf_token %}
    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.first_name }}
        <label class="form-label" style="margin-left: 0px;">Nombre</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.last_name }}
        <label class="form-label" style="margin-left: 0px;">Apellido</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_superuser }}
        <label class="form-label" style="margin-left: 0px;">Superuser</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_staff }}
        <label class="form-label" style="margin-left: 0px;">Staff</label>
    </div>
    
    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_active }}
        <label class="form-label" style="margin-left: 0px;">Activo</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.bio }}
        <label class="form-label" style="margin-left: 0px;">Bio</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.profile_pic }}
        <label class="form-label" style="margin-left: 0px;">imagen</label>
    </div>    

    <button class="btn btn-primary btn-block mb-3" type="submit">Grabar</button>
</form>
{% endblock %}