django_base/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django_base.views import index, sobrenosotros
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('paginas/', include('paginas.urls')),
    path('',  include('users.urls', namespace='users')),
    path('sobre-nosotros/', sobrenosotros, name ='sobrenosotros')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('borrar/<slug:slug>', views.borrar_usuario, name = 'borrar'),
    path('edit/<slug:slug>', views.edituser_list, name = 'edit'),
    path('edit2/<slug:slug>', views.edituser_view, name = 'edit2'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path('signup/', views.signup_view, name='signup'),   
    path('logout/', views.logout_view, name='logout'),
    path('change/',views.changepassword, name='change'),
    path('list/', views.user_list, name = 'list'),
    path('crear/', views.signup_view, name = 'crear'),

]

users/models.py
import random
import string

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from paginas.models import Paginas


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class CustomAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, **other_fields):

        if not email:
            raise ValueError(_('Teclea una cuenta de correo valida'))

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        if other_fields.get('is_staff') is not True:
            raise ValueError('Si es de staff debe ser un Superusuario')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('si se esta creando un Superusuario debe asignarse como verdadero is_superuser')
        return self.create_user(email, first_name, last_name, password, **other_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to='users/', default='users/default.png')
    bio = models.TextField(_('Bio'), max_length=500, blank=True)
    followers = models.ManyToManyField(
        "self",
        related_name='following',
        symmetrical=False,
        blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    register_date = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.slug])

    #def get_absolute_url2(self):
    #    return reverse('users:edituser_view', args=[self.slug])        

    def count_following(self):
        users_following = UserProfile.objects.filter(followers=self)
        return users_following.count()

    def count_posts(self):
        return Paginas.objects.filter(autor=self).count()

    def is_follower(self, other_user):
        if other_user in self.followers.all():
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.email)
        super(UserProfile, self).save(*args, **kwargs)

users/forms.py
from unittest.util import _MAX_LENGTH
from django import forms

from users.models import UserProfile

class UserChangePassword(forms.Form):
    old_password = forms.CharField(
                widget=forms.PasswordInput(
                attrs={
                'id': 'old_password',
                'type': 'password',
                'class': 'form-control'
            }
        ))
    new_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'new_password',
                'type': 'password',
                'class': 'form-control'
            }
        ))
    reenter_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'reenter_password',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    def clean_reenter_password(self):
        cd = self.cleaned_data
        if cd['new_password'] != cd['reenter_password']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['reenter_password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'loginEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'loginPassword',
            'type': 'password',
            'class': 'form-control',
        })
    )


class UserSignUpForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'signupEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    first_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    last_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'signupPassword',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control'
            }
        ))

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['password2']



class EditUserForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['password','last_login','email','slug','register_date','groups','user_permissions','followers']

    # first_name = forms.CharField(
    #     max_length=100,
    #     widget=forms.TextInput(
    #         attrs={
    #             'type': 'text',
    #             'class': 'form-control'
    #         }
    #     ))

#    last_name = forms.CharField(
#        max_length=100,
#        widget=forms.TextInput(
#            attrs={
#                'type': 'text',
#                'class': 'form-control'
#            }
#        ))

    # profile_pic=forms.ImageField(
    #     )

    # bio = forms.CharField(
    #     widget=forms.Textarea(
    #         attrs={
    #             'type': 'text',
    #             'class': 'form-control'
    #         }
    #     ))

    # is_superuser = forms.BooleanField(
    #     widget=forms.CheckboxInput())

    # is_staff = forms.BooleanField(
    #     widget=forms.CheckboxInput())

    # is_active = forms.BooleanField(
    #     widget=forms.CheckboxInput())

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from users.context_processors import edituser_form
from paginas.models import Secciones
from users.models import UserProfile

from .forms import UserLoginForm, UserSignUpForm, UserChangePassword, EditUserForm


def login_view(request):
    login_form = UserLoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            #messages.success(request, 'Has iniciado sesion correctamente')
            return redirect('index')
        else:
            messages.warning(
                request, 'Correo Electronico o Contraseña invalida')
            return redirect('index')

    messages.error(request, 'Formulario Invalido')
    return redirect('index')


def signup_view(request):
    signup_form = UserSignUpForm(request.POST or None)
    if signup_form.is_valid():
        email = signup_form.cleaned_data.get('email')
        first_name = signup_form.cleaned_data.get('first_name')
        last_name = signup_form.cleaned_data.get('last_name')
        password = signup_form.cleaned_data.get('password')
        try:
            user = get_user_model().objects.create(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=make_password(password),
                is_active=True
            )
            login(request, user)
            return redirect('index')

        except Exception as e:
            print(e)
            return JsonResponse({'detail': f'{e}'})
    messages.warning(request, 'Las Contraseñas no coinciden')
    return redirect('index')    

def changepassword(request):
    ChangePassword = UserChangePassword(request.POST or None)
    if ChangePassword.is_valid():
        old_password = ChangePassword.cleaned_data.get('old_password')
        new_password = ChangePassword.cleaned_data.get('new_password')
        reenter_password = ChangePassword.cleaned_data.get('reenter_password')
        try:
            user = get_user_model().objects.update(
                password=make_password(new_password),
            )
            messages.success(request, 'Contraseña cambiada, ingresa nuevamente')
            return redirect('index')
        except Exception as e:
            print(e)
            return JsonResponse({'detail': f'{e}'})
    messages.warning(request, 'Las Contraseñas no coinciden')
    return redirect('index')


def edituser_list(request, slug):
    user_detail = get_object_or_404(get_user_model(), slug=slug)
    if request.method == 'POST':
        form = EditUserForm(request.POST, request.FILES, instance = user_detail)
        if form.is_valid():
            form.save()
            return redirect("/list")
    else:
        form = EditUserForm(instance = user_detail)
        context = {'form':form,'slug':slug}
        return render(request, 'user/user_edit2.html',context)

def edituser_view(request, slug):
    user_detail = get_object_or_404(get_user_model(), slug=slug)
    if request.method == 'POST':
        form = EditUserForm(request.POST, request.FILES, instance = user_detail)
        if form.is_valid():
            form.save()
            return redirect("/profile")
    else:
        form = EditUserForm(instance = user_detail)
        context = {'form':form,'slug':slug}
        return render(request, 'user/user_edit2.html',context)        


def borrar_usuario(request, slug):
    user_detail = get_object_or_404(get_user_model(), slug=slug)
    try:
        if request.method == 'GET':
            secciones = Secciones.objects.filter(habilitada=True).order_by('nombre')
            context = {'user_detail':user_detail, 'secciones':secciones}
            return render(request, 'user/borrar_usuario.html', context=context)
        else:
            user_detail.delete()
            context = {'user_detail':user_detail}
            return redirect("/list")
        
    except:
        context = {'error':'El usuario no existe'}
        return render(request, 'user/borrar_usuario.html', context=context)

















    try:
        if request.method == 'POST':
            user_detail.delete()            
            return redirect("/list")
    except:
        messages.warning(request, 'Usuario no eliminado')         
        return redirect('/list')


    #usuario = get_object_or_404(get_user_model(), slug=slug)
    #if not request.user.is_authenticated:
    #    messages.warning(request, 'Debes iniciar sesion')
    #else:
    #    edituser_form = EditUserForm(request.POST,usuario)
    #    if edituser_form.is_valid():
    #        first_name   = EditUserForm.cleaned_data.get('first_name')
    #        last_name    = EditUserForm.cleaned_data.get('last_name')
    #        is_superuser = EditUserForm.cleaned_data.get('is_superuser')
    #        is_staff     = EditUserForm.cleaned_data.get('is_staff')
    #        is_active    = EditUserForm.cleaned_data.get('is_active')
    #        bio          = EditUserForm.cleaned_data.get('bio')
    #        profile_pic  = EditUserForm.cleaned_data.get('profile_pic')
    #        try:
    #            user = get_user_model().objects.update(
    #                first_name=first_name,
    #                last_name=last_name,
    #                is_superuser=is_superuser,
    #                is_staff = is_staff,
    #                is_active=is_active,
    #               bio=bio,
    #                profile_pic=profile_pic
    #            )
    #            return redirect('index')
    #        except Exception as e:
    #            print(e)
    #            return JsonResponse({'detail': f'{e}'})
    #    messages.warning(request, 'Datos incorrectos')
    #    return redirect('index')



def logout_view(request):
    logout(request)
    return redirect('index')


@login_required(login_url='index')
def profile_view(request):
    return render(request, 'user/profile.html')


@login_required(login_url='index')
def user_list(request): 
    usuarios = UserProfile.objects.all
    context = {'users':usuarios}
    return render(request,'user/user_list.html',context=context)    


def user_detail(request, slug):
    user_detail = get_object_or_404(get_user_model(), slug=slug)
    if not request.user.is_authenticated:
        messages.warning(request, 'Debes iniciar sesion')

    return render(request, 'user/user_detail.html', {'user_detail': user_detail})


@login_required(login_url='index')
def follow(request, slug):
    to_follow = get_object_or_404(get_user_model(), slug=slug)
    if to_follow.is_follower(request.user):
        to_follow.followers.remove(request.user)
    else:
        to_follow.followers.add(request.user)
    to_follow.save
    return redirect(to_follow)

templates/user/borrar_usuario.html
{% extends 'base_backoffice.html' %}

{% block titulo %}
    Borrar Usuario
{% endblock %}

{% block contenido %}


    <h3 style="color: red">Estas por eliminar el usuario, estas seguro?</h3>

    <form method = "POST">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Eliminar</button>
    </form>


{% endblock %}

templates/user/change_password.html
<!-- Modal -->
<div class="modal fade" id="modal_change" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Cambiar Contraseña</h4>
            </div>
            <div class="modal-body"> 
                            <form id="change" class="text-center" action="{% url 'users:change' %}" method="post">
                                {% csrf_token %}
                                <div class="form-outline form-auth-md mb-4">
                                    {{ changepassword.old_password }}
                                    <label class="form-label" style="margin-left: 0px;">Contraseña actual</label>
                                </div>
                                <div class="form-outline form-auth-md mb-4">
                                    {{ changepassword.new_password }}
                                    <label class="form-label" style="margin-left: 0px;">Nueva Contraseña</label>
                                </div>
                                <div class="form-outline form-auth-md mb-4">
                                    {{ changepassword.reenter_password }}
                                    <label class="form-label" style="margin-left: 0px;">Repetir Contraseña</label>
                                </div>
                                <button type="submit" class="btn btn-primary btn-block mb-4">Grabar</button>
                            </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

templates/user/login.html
<!-- Modal -->
<div class="modal fade" id="modal_login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>

                </button>
                <h4 class="modal-title" id="myModalLabel">Iniciar Sesion / Registrarse</h4>

            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#iniciar_sesion" aria-controls="iniciar_sesion" role="tab" data-toggle="tab">Iniciar Sesion</a>

                        </li>
                        <li role="presentation"><a href="#registrarse" aria-controls="registrarse" role="tab" data-toggle="tab">Registrarse</a>

                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <!--
                        <div role="tabpanel" class="tab-pane active" id="uploadTab">Iniciar Sesion</div>
                        <div role="tabpanel" class="tab-pane" id="browseTab">Registrarse</div>
                        -->
                        <div class="tab-pane active" id="iniciar_sesion" role="tabpanel">
                          <form id="login" class="text-center" action="{% url 'users:login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-outline form-auth-md mb-4">
                              {{ loginForm.email }}
                              <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                            </div>
                            <div class="form-outline form-auth-md mb-4">
                              {{ loginForm.password }}
                              <label class="form-label" style="margin-left: 0px;">Contraseña</label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar</button>
                          </form>
                        </div>

                        <div class="tab-pane fade" id="registrarse" role="tabpanel">
                          <form id="register" class="text-center" action="{% url 'users:signup'%}" method="post">
                            {% csrf_token %}
                            <div class="form-outline form-auth-mdb mb-4">
                              {{ signupForm.email}}
                              <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                            </div>
              
                            <div class="form-outline form-auth-mdb mb-4">
                              {{ signupForm.first_name }}
                              <label class="form-label" style="margin-left: 0px;">Nombre</label>
                            </div>
              
                            <div class="form-outline form-auth-mdb mb-4">
                              {{ signupForm.last_name }}
                              <label class="form-label" style="margin-left: 0px;">Apellido</label>
                            </div>
              
                            <div class="form-outline form-auth-mdb mb-4">
                              {{ signupForm.password }}
                              <label class="form-label" style="margin-left: 0px;">Password
                              </label>
                            </div>
              
                            <div class="form-outline form-auth-mdb mb-4">
                              {{ signupForm.password2 }}
                              <label class="form-label" style="margin-left: 0px;">Repetir
                              </label>
              
                            </div>
              
                            <button class="btn btn-primary btn-block mb-3" type="submit">Registrar</button>
                          </form>
              
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>




<!-- Modal -->
<!--<div class="modal fade" id="loginModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <ul class="nav nav-pills nav-justified mb-3">
          <li class="nav-item">
            <a class="nav-link active show" data-mdb-toggle="pill" href="#navbarLogin-login" role="tab">
              Iniciar Sesion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-mdb-toggle="pill" href="#navbarLogin-signup" role="tab">Registrarse</a>
          </li>
        </ul>

        <div class="tab-content" id="tab-content">
          <div class="tab-pane fade show active" id="navbarLogin-login" role="tabpanel">
            <form id="login" class="text-center" action="{% url 'users:login' %}" method="post">
              {% csrf_token %}

              <div class="form-outline form-auth-md mb-4">
                {{ loginForm.email }}
                <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
              </div>

              <div class="form-outline form-auth-md mb-4">
                {{ loginForm.password }}
                <label class="form-label" style="margin-left: 0px;">Contraseña</label>
              </div>



              <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar</button>
            </form>
          </div>


          <div class="tab-pane fade" id="navbarLogin-signup" role="tabpanel">
            <form id="register" class="text-center" action="{% url 'users:signup'%}" method="post">
              {% csrf_token %}
              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.email}}
                <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.first_name }}
                <label class="form-label" style="margin-left: 0px;">Nombre</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.last_name }}
                <label class="form-label" style="margin-left: 0px;">Apellido</label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.password }}
                <label class="form-label" style="margin-left: 0px;">Contraseña
                </label>
              </div>

              <div class="form-outline form-auth-mdb mb-4">
                {{ signupForm.password2 }}
                <label class="form-label" style="margin-left: 0px;">Repetir
                </label>

              </div>

              <button class="btn btn-primary btn-block mb-3" type="submit">Registrar</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
-->

templates/user/profile.html
{% extends "../base_backoffice.html" %}
{% block contenido %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user.profile_pic.url }} height="240" width="240" alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title mb-4">{{ user.first_name}} {{ user.last_name}}</h4>
            <p class="col-4 mb-0">Publicaciones <strong>{{ user.count_posts }}</strong></p>
            <p class="col-4 mb-0">Seguidores <strong>{{ user.followers.all|length }}</strong></p>
            <p class="col-4 mb-0">Seguidos <strong>{{ user.count_following }}</strong></p>
            <p class="col-4 nter"></p>
            <p class="card-text mb-5">{{ user.bio }}</p>
            <p class="col-4">
              {% if request.user.is_superuser %} 
                <a class='btn btn-rounded col-5' style="background-color: #55694e; color: #FFFFFF;" href="/edit2/{{user.slug}}" style="color: #FFFFFF;">Editar</a>
              {% endif %}
              <a class='btn btn-rounded col-5' style="background-color: #b30707; color: #FFFFFF;" href={% url 'users:logout'%}>Cerrar Sesion</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/user/user_detail.html
{% extends "base_backoffice.html" %}
{% block contenido %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user_detail.profile_pic.url }} height="240" width="240" alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title mb-4">{{ user_detail.first_name}} {{ user_detail.last_name}}</h4>
            <p class="col-4 mb-0">Publicaciones <strong>{{ user_detail.count_posts }}</strong></p>
            <p class="col-4 mb-0">Seguidores <strong>{{ user_detail.followers.all|length }}</strong></p>
            <p class="col-4 mb-0">Seguidos <strong>{{ user_detail.count_following }}</strong></p>
            <p class="col-4 nter"></p>
            <p class="card-text mb-5">{{ user_detail.bio }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/user/user_edit.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
<form id="edit" class="text-center" action="{% url 'users:edit'%}" method="post">
    {% csrf_token %}
    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.first_name }}
        <label class="form-label" style="margin-left: 0px;">Nombre</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.last_name }}
        <label class="form-label" style="margin-left: 0px;">Apellido</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_superuser }}
        <label class="form-label" style="margin-left: 0px;">Superuser</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_staff }}
        <label class="form-label" style="margin-left: 0px;">Staff</label>
    </div>
    
    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.is_active }}
        <label class="form-label" style="margin-left: 0px;">Activo</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.bio }}
        <label class="form-label" style="margin-left: 0px;">Bio</label>
    </div>

    <div class="form-outline form-auth-mdb mb-4">
        {{ edituserform.profile_pic }}
        <label class="form-label" style="margin-left: 0px;">imagen</label>
    </div>    

    <button class="btn btn-primary btn-block mb-3" type="submit">Grabar</button>
</form>
{% endblock %}

templates/user/user_edit2.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
        <h2 style="margin-left:30rem">Complete los campos a actualizar</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table wifth="100%">
                {{form.media}}
                {{form.as_table}}
            </table>
            <input type="submit" , value="Enviar">
        </form>
{% endblock %}

templates/user/user_list.html
{% extends 'base_backoffice.html' %}
{% block contenido %}
<table width="100%" class="table-bordered">
<tr style="background-color: black; color: white;">
    <td></td>
    <td>Correo</td>
    <td>Nombre completo</td>
    <td>Bio</td>
    <td></td>
    <td></td>
    <td></td>
</tr>
{% for user in users %}
<tr>
        <td>
            {% if user.profile_pic %}
                <img src="{{user.profile_pic.url}}" class="card-img-top" height="60" width='60' alt="" loading="lazy" >
            {% endif %}
        </td>
        <td>
            {{user.email}}
        </td>
        <td>
            {{user.first_name}} {{user.last_name}}
        </td>
        <td>
            {{user.bio}}
        </td>
        <td style="background-color: black; color: white; text-align: center;">
            <a href={{user.get_absolute_url}} style="color: white;" >Ver mas!</a>
        </td>    
        <td style="background-color: #55694e; color: #FFFFFF; text-align: center;">
            <a href="/edit/{{user.slug}}" style="color: #FFFFFF;" >EDITAR</a>
        </td> 
        <td style="background-color: #4d1e23; color: white; text-align: center;">
            <a href="/borrar/{{user.slug}}" style="color: #FFFFFF;">ELIMINAR</a>
        </td>                 
</tr>
{% endfor %}
</table>
{% endblock %}